site_name: X-Ray Selection Tools
repo_url: https://github.com/MarshmallowCirno/XRay_Selection_Tools


nav:
    - Get Started:
      - Introduction: index.md
      - installation.md

    - Preferences:
      - Mesh tools: mesh_prefs.md
      - Object tools : object_prefs.md
      - Advanced Keymap: keymap_prefs.md

    - Development:
      - Changelog: changelog.md


theme:
    name: readthedocs
    include_homepage_in_sidebar: False

markdown_extensions:
  - admonition

extra_css:
  - stylesheets/extra.css